version: 2
jobs:
  build:
    docker:
      - image: python:2.7
        environment:
          CONFIG: test
          DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
      - image: postgres:9.5.5
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    working_directory: /home/ubuntu/training
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Tests
          command: python manage.py test
      - store_artifacts:
          path: cover/coverage
          destination: reports
      - store_test_results:
          path: "cover/"
